### PR TITLE
[WIP] Driver redesign

### PR DESCRIPTION
**Pull request by darnould**
## Problem
Decoration required `DelegatingLogger`s to be sandwiched between the various decorators.  Unnecessary complexity.

## Solution
A list of drivers (analogous to "decorators") given to `Alephant::Logger` - each method call to the logger is sent to each driver that can `respond_to?` it.

**Major release**.

### CODE REVIEW

**Comment by revett** [comment]
@darnould - is ready for me to test with Statsd?

**Comment by darnould** [comment]
Give it a crack @revett

**Comment by revett** [comment]
@darnould Can you update the README within this PR as well please?

**Comment by darnould** [comment]
@revett - will update the docs in this PR once you've successfully validated it with statsd & a consuming application. May well be subject to change pending that outcome

**Pull request closed without merging**
